module.exports = {
  reception: [
    'receptionNumber',
    'familyId',
    'date',
    'visitorName',
    'purposeOfVisit',
    'caseMovedTo',
    '_id',
    'caseClosed',
    'newCase'
  ],
  assistance: [
    'cost',
    'familyId',
    'supportNeeded.date',
    'supportNeeded.description',
    'assistanceCategory',
    'assistanceId',
    'familyId',
    '_id'
  ],
  borrow: [
    'formId',
    'familyId',
    'familyName',
    'recipientName',
    'department',
    'nameOfEmployee',
    'dateOfBorrow',
    'dateOfReturn',
    '_id'
  ],
  family: [
    '_id',
    'wife.wifeName',
    'wife.wifePhone',
    'wife.wifeCivilId',
    'husband.husbandName',
    'husband.husbandPhone',
    'husband.husbandCivilId',
    'dateOfCaseStudy',
    'familyId',
    'formId',
    'isRamadan',
    'familyAddress.state',
    'familyAddress.town',
    'isArchived',
    'reasonForArchiving',
    'typeOfAssistanceNeeded',
    'insolventFamilies.insolventFamilyId',
    'insolventFamilies.insolventFamilyNotes',
    'insolventFamilies.isActive'
    // 'numberOfChildrenInElementary',
    // 'numberOfChildrenInSecondary',
    // 'numberOfChildrenInHighSchool',
    // 'numberOfChildrenInHigherEducation'
  ],
  ramadan: [
    'wife.wifeName',
    'wife.wifePhone',
    'wife.wifeCivilId',
    'husband.husbandName',
    'husband.husbandPhone',
    'husband.husbandCivilId',
    'familyId',
    'ramadan',
    'formId',
    'familyAddress.state',
    '_id'
  ],
  ramadanOne: [
    'wife.wifeName',
    'wife.wifePhone',
    'wife.wifeCivilId',
    'husband.husbandName',
    'husband.husbandPhone',
    'husband.husbandCivilId',
    'familyId',
    'ramadan',
    'formId',
    'signature',
    'familyAddress.state',
    '_id'
  ],
  eidAlAdha: [
    'wife.wifeName',
    'wife.wifePhone',
    'wife.wifeCivilId',
    'husband.husbandName',
    'husband.husbandPhone',
    'husband.husbandCivilId',
    'familyId',
    'eidAlAdha',
    'formId',
    'familyAddress.state',
    '_id'
  ],
  eidAlAdhOne: [
    'wife.wifeName',
    'wife.wifePhone',
    'wife.wifeCivilId',
    'husband.husbandName',
    'husband.husbandPhone',
    'husband.husbandCivilId',
    'familyId',
    'formId',
    'eidAlAdha',
    'familyAddress.state',
    '_id'
  ],
  report: [
    'typeOfAssistanceNeeded',
    'dateOfCaseStudy',
    'claimMadeBy',
    'formId',
    'familyCategory',
    'wife.wifeName',
    'wife.wifePhone',
    'wife.wifeCivilId',
    'husband.husbandName',
    'husband.husbandCivilId',
    'husband.husbandPhone',
    'familyId',
    '-_id'
  ],
  familyMembers: [
    'familyAddress',
    'typeOfAssistanceNeeded',
    'familyCategory',
    'husband',
    'wife',
    'income',
    'familyId',
    '-_id'
  ],
  orphanFamilies: [
    'familyAddress',
    'husband.husbandName',
    'husband.husbandCivilId',
    'husband.husbandPhone',
    'familyCategory',
    'wife.wifeName',
    'guardian.guardianName',
    'wife.wifeCivilId',
    'wife.wifePhone',
    'formId',
    'familyId',
    '-_id'
  ],
  insolventFamilies: [
    '_id',
    'claimMadeBy',
    'husband.husbandName',
    'husband.husbandPhone',
    'wife.wifeName',
    'wife.wifePhone',
    'accommodationStatus.rent',
    'livingCondition',
    'familyAddress',
    'numberOfChildrenInElementary',
    'numberOfChildrenInSecondary',
    'numberOfChildrenInHighSchool',
    'income',
    'loan',
    'formId',
    'typeOfAssistanceNeeded',
    // 'lowIncomeFamilyId',
    // 'notes',
    // main not family
    'insolventFamilies.insolventFamilyId',
    'insolventFamilies.insolventFamilyNotes',
    'insolventFamilies.isActive'
    // 'typeOfAssistanceNeeded'
  ],
  possibleProductiveFamilies: [
    'formId',
    'claimMadeBy',
    'wife',
    'familyAddress',
    'income',
    'accommodationStatus.rentAmount',
    'accommodationStatus.lateElectricalAmount',
    'accommodationStatus.lateWaterAmount',
    'loan.housingLoanAmount',
    'loan.personalLoanAmount',
    'loan.vehicleLoanAmount',
    '-_id'
  ],
  productiveFamilies: [
    '_id',
    'formId',
    'nameOfRecipient',
    'relationship',
    'ageOfRecipient',
    'RecipientNationalId',
    'RecipientEducationLevel',
    'fieldOfWork',
    'formOfContact',
    'dateOfContact',
    'reasonForNotRegistering'
  ],
  orphanSponsors: [
    'sponsorName',
    'sponsorId',
    'sponsorPhone',
    'numberOfSponsored',
    'sponsorAmount',
    'paymentMethod',
    'sponsorStatus',
    'sponsorBankAccountNum',
    'sponsorBank',
    'hasSponsorship',
    'hasPayments'
  ]
}
